service: bluebird-weather

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  httpApi:
    cors: true

functions:
  notifier:
    handler: todos/notifier.notifier
    events:
      - httpApi:
          path: /signup
          method: posts
