
puts("Seeding")

#Resorts
vail = Resort.create(name: "https://imgur.com/1r06XI2.jpg", map: "https://cdn.ski/fSnxSfpdLWx33KYc.jpeg")
breckenridge = Resort.create(name: "https://i.imgur.com/3kYQrCK.jpg", map: "https://www.skicentral.com/images/trailmaps/303007-2400.jpg")
keystone = Resort.create(name: "https://i.imgur.com/AEU5hd0.jpg", map: "https://skimap.org/data/519/4070/1608579537jpg_render.jpg")
copper = Resort.create(name: "https://i.imgur.com/Pbok6pV.jpg", map: "https://skimap.org/data/509/2200/1637367968.png")
loon = Resort.create(name: "https://i.imgur.com/Su6NkPI.jpg", map: "https://res.cloudinary.com/liftopia/image/upload/c_fit,d_defaults:default_logo_1.png,f_auto,h_980,q_auto,w_980/v1/production/trail_maps/Loon_TrailMap18.19_58ab850f3eefdcc76b5e16f6ebbe52ba")
telluride = Resort.create(name: "https://i.imgur.com/iaAoCD6.jpg", map: "https://s3.onthesnow.com/images/trailmaps/colorado/telluride/20181004155715/large.jpg")
stowe = Resort.create(name: "https://i.imgur.com/NV0LYjq.jpg", map: "https://skimap.org/data/212/3535/1635228546jpg_render.jpg")
okemo = Resort.create(name: "https://i.imgur.com/jjmGiRZ.jpg", map: "https://s3.onthesnow.com/images/trailmaps/vermont/okemo-mountain-resort/20161118205447/xlarge.jpg")
jackson_hole = Resort.create(name: "https://i.imgur.com/2EogNO9.jpg", map: "https://www.datocms-assets.com/50871/1636863909-2021-22-background-updated-outlines.jpg")
big_sky = Resort.create(name: "https://i.imgur.com/Q8WAhL9.jpg", map: "https://skimap.org/data/361/7/1257012299jpg_render.jpg")
park_city = Resort.create(name: "https://i.imgur.com/Xr0KQuB.jpg", map: "https://dam-assets.vailresorts.com/is/image/vailresorts/2223_PC_TrailMapArt_digital_partners?resMode=sharp2&w=1728&h=1247&wid=392&fit=constrain,1&dpr=on,2.625")
killington = Resort.create(name: "https://i.imgur.com/pDG978B.jpg", map: "https://www.newenglandskihistory.com/maps/Vermont/killington/killingtonmap-2000-0000a.jpg")


# okemo https://s3.onthesnow.com/images/trailmaps/vermont/okemo-mountain-resort/20161118205447/xlarge.jpg
# jackson hole https://www.datocms-assets.com/50871/1636863909-2021-22-background-updated-outlines.jpg
# big sky https://skimap.org/data/361/7/1257012299jpg_render.jpg
# park city https://dam-assets.vailresorts.com/is/image/vailresorts/2223_PC_TrailMapArt_digital_partners?resMode=sharp2&w=1728&h=1247&wid=392&fit=constrain,1&dpr=on,2.625

#Users
john = User.create(username:"jmckinnon10", password: "12345678", first_name:"John", last_name:"McKinnon")
tommy = User.create(username:"tlusk", password:"12345678", first_name:"Tommy", last_name:"Lusk")
dan = User.create(username:"dferraro", password:"12345678", first_name:"Dan", last_name:"Ferraro")
chance = User.create(username:"cmarrocco", password:"12345678", first_name:"Chance", last_name:"Marrocco")

#Trails
hunky_dory = Trail.create(name:"Hunky Dory ", difficulty: "🟦", resort_id: vail.id)
cloud_nine = Trail.create(name:"Cloud 9 ", difficulty: "🟦", resort_id: vail.id)
chopstix = Trail.create(name:"Chopstix ", difficulty: "🟦", resort_id: vail.id)
black_forest = Trail.create(name:"Black Forest ", difficulty: "🟦", resort_id: vail.id)
klickity_klack = Trail.create(name:"Klickity Klack", difficulty: "♦", resort_id: vail.id)
dragons_teeth = Trail.create(name:"Dragons Teeth", difficulty: "♦", resort_id: vail.id)
shangri_la = Trail.create(name:"Shangri-La", difficulty: "♦", resort_id: vail.id)
look_ma = Trail.create(name:"Look Ma", difficulty: "♦", resort_id: vail.id)
steep_and_deep = Trail.create(name:"Steep and Deep", difficulty: "♦♦", resort_id: vail.id)
prima_cornice = Trail.create(name:"Prima Cornice", difficulty: "♦♦", resort_id: vail.id)
deja_vu = Trail.create(name:"Deja Vu ", difficulty: "🟦", resort_id: breckenridge.id)
pioneer = Trail.create(name:"Pioneer ", difficulty: "🟦", resort_id: breckenridge.id)
cashier = Trail.create(name:"Cashier ", difficulty: "🟦", resort_id: breckenridge.id)
spit_fire = Trail.create(name:"Spit Fire", difficulty: "♦", resort_id: breckenridge.id)
adios = Trail.create(name:"Adios", difficulty: "♦", resort_id: breckenridge.id)
dark_rider = Trail.create(name:"Dark Rider", difficulty: "♦", resort_id: breckenridge.id)
lower_boneyard = Trail.create(name:"Lower Boneyard", difficulty: "♦", resort_id: breckenridge.id)
spruce = Trail.create(name:"Spruce", difficulty: "♦", resort_id: breckenridge.id)
quiver = Trail.create(name:"Quiver", difficulty: "♦♦", resort_id: breckenridge.id)
mach_one = Trail.create(name:"Mach One", difficulty: "♦♦", resort_id: breckenridge.id)
river_run = Trail.create(name:"River Run ", difficulty: "🟦", resort_id: keystone.id)
anticipation = Trail.create(name:"Anticipation ", difficulty: "🟦", resort_id: keystone.id)
last_hoot = Trail.create(name:"Last Hoot", difficulty: "♦", resort_id: keystone.id)
mineshaft = Trail.create(name:"Mineshaft", difficulty: "♦", resort_id: keystone.id)
geronimo = Trail.create(name:"Geronimo", difficulty: "♦", resort_id: keystone.id)
black_hawk = Trail.create(name:"Black Hawk", difficulty: "♦", resort_id: keystone.id)
bullet_glades = Trail.create(name:"Bullet Glades", difficulty: "♦", resort_id: keystone.id)
the_wolf_den = Trail.create(name:"The Wolf Den", difficulty: "♦", resort_id: keystone.id)
ambush = Trail.create(name:"Ambush", difficulty: "♦", resort_id: keystone.id)
snake_pit = Trail.create(name:"Snake Pit", difficulty: "♦♦", resort_id: keystone.id)
buck_shot = Trail.create(name:"Buck Shot", difficulty: "♦♦", resort_id: keystone.id)
collage = Trail.create(name:"Collage ", difficulty: "🟦", resort_id: copper.id)
american_flyer = Trail.create(name:"American Flyer ", difficulty: "🟦", resort_id: copper.id)
gold_digger = Trail.create(name:"Gold Digger", difficulty: "♦", resort_id: copper.id)
revenge = Trail.create(name:"Revenge", difficulty: "♦", resort_id: copper.id)
slip_not = Trail.create(name:"Slip Not", difficulty: "♦", resort_id: copper.id)
formidable = Trail.create(name:"Formidable", difficulty: "♦", resort_id: copper.id)
far_west = Trail.create(name:"Far West", difficulty: "♦", resort_id: copper.id)
drain_pipe = Trail.create(name:"Drain Pipe", difficulty: "♦♦", resort_id: copper.id)
buzzards_alley = Trail.create(name:"Buzzards Alley", difficulty: "♦♦", resort_id: copper.id)
buffalo_stampede = Trail.create(name:"Buffalo Stampede", difficulty: "♦♦", resort_id: copper.id)
bear_pause = Trail.create(name:"Bear Pause ", difficulty: "🟦", resort_id: loon.id)
blue_ox = Trail.create(name:"Blue Ox", difficulty: "🟦", resort_id: loon.id)
lower_twitcher = Trail.create(name:"Lower Twitcher", difficulty: "♦", resort_id: loon.id)
angel_street = Trail.create(name:"Angel Street", difficulty: "♦", resort_id: loon.id)
skidder = Trail.create(name:"Skidder", difficulty: "♦", resort_id: loon.id)
boss_woods = Trail.create(name:"Boss Woods", difficulty: "♦", resort_id: loon.id)
bucksaw = Trail.create(name:"Bucksaw", difficulty: "♦", resort_id: loon.id)
triple_trouble = Trail.create(name:"Triple Trouble", difficulty: "♦", resort_id: loon.id)
big_dipper = Trail.create(name:"Big Dipper", difficulty: "♦", resort_id: loon.id)
ripsaw = Trail.create(name:"Ripsaw", difficulty: "♦♦", resort_id: loon.id)
lower_lookout = Trail.create(name:"Lower Lookout ", difficulty: "🟦", resort_id: telluride.id)
peek_a_boo = Trail.create(name:"Peek-A-Boo ", difficulty: "🟦", resort_id: telluride.id)
smuggler = Trail.create(name:"Smuggler ", difficulty: "🟦", resort_id: telluride.id)
apex = Trail.create(name:"Apex", difficulty: "♦", resort_id: telluride.id)
chongos = Trail.create(name:"Chongos", difficulty: "♦", resort_id: telluride.id)
pandora = Trail.create(name:"Pandora", difficulty: "♦", resort_id: telluride.id)
bushwacker = Trail.create(name:"Bushwacker", difficulty: "♦", resort_id: telluride.id)
giant_steps = Trail.create(name:"Giant Steps", difficulty: "♦♦", resort_id: telluride.id)
north_chute = Trail.create(name:"North Chute", difficulty: "♦♦", resort_id: telluride.id)
mine_shaft = Trail.create(name:"Mine Shaft", difficulty: "♦♦", resort_id: telluride.id)
tyro = Trail.create(name:"Tyro ", difficulty: "🟦", resort_id: stowe.id)
ridgeview = Trail.create(name:"Ridgeview ", difficulty: "🟦", resort_id: stowe.id)
midway = Trail.create(name:"Midway", difficulty: "♦", resort_id: stowe.id)
upper_hayride = Trail.create(name:"Upper Hayride", difficulty: "♦", resort_id: stowe.id)
centerline = Trail.create(name:"Centerline", difficulty: "♦", resort_id: stowe.id)
maiden_lane = Trail.create(name:"Maiden Lane", difficulty: "♦", resort_id: stowe.id)
upper_smugglers = Trail.create(name:"Upper Smugglers", difficulty: "♦", resort_id: stowe.id)
chin_clip = Trail.create(name:"Chin Clip", difficulty: "♦", resort_id: stowe.id)
upper_star = Trail.create(name:"Upper Star", difficulty: "♦♦", resort_id: stowe.id)
goat = Trail.create(name:"Goat", difficulty: "♦♦", resort_id: stowe.id)
blue_moon = Trail.create(name:"Blue Moon ", difficulty: "🟦", resort_id: okemo.id)
lower_limelight = Trail.create(name:"Lower LimeLight ", difficulty: "🟦", resort_id: okemo.id)
tuckered_out = Trail.create(name:"Tuckered Out ", difficulty: "🟦", resort_id: okemo.id)
vortex = Trail.create(name:"Vortex", difficulty: "♦", resort_id: okemo.id)
fast_lane = Trail.create(name:"Fast Lane", difficulty: "♦", resort_id: okemo.id)
ledges = Trail.create(name:"Ledges", difficulty: "♦", resort_id: okemo.id)
lower_sels = Trail.create(name:"Lower Sel's", difficulty: "♦", resort_id: okemo.id)
upper_wild_wing = Trail.create(name:"Upper Wild Wing", difficulty: "♦♦", resort_id: okemo.id)
loose_spruce = Trail.create(name:"Loose Spruce", difficulty: "♦♦", resort_id: okemo.id)
outrage = Trail.create(name:"Outrage", difficulty: "♦♦", resort_id: okemo.id)
lupine_way = Trail.create(name:"Lupine Way ", difficulty: "🟦", resort_id: jackson_hole.id)
teewinot = Trail.create(name:"Teewinot", difficulty: "🟦", resort_id: jackson_hole.id)
bird_in_the_hand = Trail.create(name:"Bird in the Hand", difficulty: "♦", resort_id: jackson_hole.id)
cascade = Trail.create(name:"Cascade", difficulty: "♦", resort_id: jackson_hole.id)
split_rock = Trail.create(name:"Split Rock", difficulty: "♦", resort_id: jackson_hole.id)
wally_world = Trail.create(name:"Wally World", difficulty: "♦", resort_id: jackson_hole.id)
south_hoback = Trail.create(name:"South Hoback", difficulty: "♦", resort_id: jackson_hole.id)
rawlins_bowl = Trail.create(name:"Rawlins Bowl", difficulty: "♦", resort_id: jackson_hole.id)
downhill = Trail.create(name:"Downhill", difficulty: "♦♦", resort_id: jackson_hole.id)
broadway = Trail.create(name:"Broadway", difficulty: "♦♦", resort_id: jackson_hole.id)
jack_rabbit = Trail.create(name:"Jack Rabbit ", difficulty: "🟦", resort_id: big_sky.id)
whiskey = Trail.create(name:"Whiskey ", difficulty: "🟦", resort_id: big_sky.id)
magic_meadows = Trail.create(name:"Magic Meadows ", difficulty: "🟦", resort_id: big_sky.id)
moonlight = Trail.create(name:"Moonlight", difficulty: "♦", resort_id: big_sky.id)
bone_crusher = Trail.create(name:"Bone Crusher", difficulty: "♦", resort_id: big_sky.id)
midnight = Trail.create(name:"Midnight", difficulty: "♦", resort_id: big_sky.id)
runaway = Trail.create(name:"Runaway", difficulty: "♦", resort_id: big_sky.id)
white_bark = Trail.create(name:"White Bark", difficulty: "♦", resort_id: big_sky.id)
three_forks = Trail.create(name:"Three Forks", difficulty: "♦♦", resort_id: big_sky.id)
crons = Trail.create(name:"Cron's", difficulty: "♦♦", resort_id: big_sky.id)
creole = Trail.create(name:"Creole ", difficulty: "🟦", resort_id: park_city.id)
dividend = Trail.create(name:"Dividend ", difficulty: "🟦", resort_id: park_city.id)
crescent = Trail.create(name:"Crescent", difficulty: "♦", resort_id: park_city.id)
nail_driver = Trail.create(name:"Nail Driver", difficulty: "♦", resort_id: park_city.id)
buckeye = Trail.create(name:"Buckeye", difficulty: "♦", resort_id: park_city.id)
belmont = Trail.create(name:"Belmont", difficulty: "♦", resort_id: park_city.id)
tenth_mountain = Trail.create(name:"10th Mountain", difficulty: "♦", resort_id: park_city.id)
bergs_bowl = Trail.create(name:"Berg's Bowl", difficulty: "♦♦", resort_id: park_city.id)
black_forest = Trail.create(name:"Black Forest", difficulty: "♦♦", resort_id: park_city.id)
blueslip_bowl = Trail.create(name:"Blueslip Bowl", difficulty: "♦♦", resort_id: park_city.id)
bear_trax = Trail.create(name:"Bear Trax ", difficulty: "🟦", resort_id: killington.id)
killink = Trail.create(name:"Killink ", difficulty: "🟦", resort_id: killington.id)
pipe_dream = Trail.create(name:"Pipe Dream ", difficulty: "🟦", resort_id: killington.id)
nowhere = Trail.create(name:"Nowhere", difficulty: "♦", resort_id: killington.id)
somewhere = Trail.create(name:"Somewhere", difficulty: "♦", resort_id: killington.id)
roundabout = Trail.create(name:"Roundabout", difficulty: "♦", resort_id: killington.id)
great_bear = Trail.create(name:"Great Bear", difficulty: "♦", resort_id: killington.id)
escapade = Trail.create(name:"Escapade", difficulty: "♦♦", resort_id: killington.id)
catwalk = Trail.create(name:"Catwalk", difficulty: "♦♦", resort_id: killington.id)
anarchy = Trail.create(name:"Anarchy", difficulty: "♦♦", resort_id: killington.id)


#Reviews
r1 = Review.create(comment: "This trail is sick", user_id: john.id, trail_id: hunky_dory.id)
r2 = Review.create(comment: "The best run at Breck", user_id: dan.id, trail_id: spit_fire.id)
r3 = Review.create(comment: "Great tree runs", user_id: dan.id, trail_id: ambush.id)
r4 = Review.create(comment: "a lot of moguls", user_id: tommy.id, trail_id: gold_digger.id)
r5 = Review.create(comment: "A ton of side hits", user_id: john.id, trail_id: dragons_teeth.id)
r6 = Review.create(comment: "Great for intermediate riders", user_id: chance.id, trail_id: hunky_dory.id)

#favorites
fav1 = Favorite.create(favorited: true, user_id: john.id, trail_id: gold_digger.id)
fav2 = Favorite.create(favorited: true, user_id: dan.id, trail_id: dragons_teeth.id)
fav3 = Favorite.create(favorited: true, user_id: dan.id, trail_id: spit_fire.id)
fav4 = Favorite.create(favorited: true, user_id: tommy.id, trail_id: ambush.id)
fav5 = Favorite.create(favorited: true, user_id: chance.id, trail_id: gold_digger.id)

puts("Seeding Done!")